CREATE TABLE [dbo].[Table1]
(
	[MA_NV] INT NOT NULL PRIMARY KEY IDENTITY, 
    [HO_TEN] NCHAR(50) NULL, 
    [GIOI_TINH] BIT NULL, 
    [CMND] VARCHAR(9) NULL, 
    [NGAY_SINH] DATETIME NULL, 
    [LUONG] DECIMAL NULL
)
